### ISSUE TITLE
Broken alias 

### ISSUE THREAD

**Issue by apzuk3** [zendframework/zend-file#15]
FilterPluginManager extends from zend-filter/FilterPluginManager and overrides $aliases which causes broken alias rename -> filterename  which doesn't exist

**Comment by weierophinney** [comment]
This is due to zend-filter 2.6 updating to be forwards-compatible with zend-servicemanager v3. Prior to 2.6, it didn't define aliases, only invokables; to make it forwards-compatible, we split invokables into aliases + factories. Unfortunately, zend-file _also_ defines aliases, which is where the problems occur.

The short term solution is to add the following to the `require` section of your `composer.json`:

``` json
"zendframework/zend-filter": "^2.5.0"
```

That will force usage of a zend-filter version from before the forwards-compatibility changes.

I plan to get zend-file updated in the next day or two, however, and, once updated, this will no longer be an issue.

**Comment by apzuk3** [comment]
I used `Zend\Filter\File\Rename` instead of alias `rename`

**Comment by weierophinney** [comment]
@aram118 That will also work. :) BTW, marking as a duplicate, as a fix was already submitted with #14, which I'll be merging shortly.
