### ISSUE TITLE
Purpose of Zend\File?

### ISSUE THREAD

**Issue by yourithielen** [zendframework/zend-file#22]
The codebase I'm working on uses `Zend\File\Transfer\Adapter\Http` to handle uploaded files. I don't know how this came about but it doesn't seem to be they way of doing things today (_edit: this seems to be the way it was done pre 2.1_). Since this is currently broken (#19) and the recommend way of uploading files uses Zend\Form (http://framework.zend.com/manual/current/en/modules/zend.form.file-upload.html) I was wondering what Zend\File is used for? I don't see any Zend component linking it as a dependency (composer.json) and there is no documentation (http://framework.zend.com/manual/current/en/modules/zend.file.class-file-locator.html).

Thanks in advance!

I found the following documentation about Zend\File\Transfer: 
- http://framework.zend.com/manual/2.0/en/modules/zend.file.transfer.introduction.html
- https://github.com/zendframework/zf2/pull/2439

**Comment by weierophinney** [comment]
The component originated in the Zend Framework 1 series, and was ported to a namespaced version with the other components when we originally started working on ZF2.

Additions to zend-filter and zend-validator for validating and handling uploaded files largely removed the need for the `Zend\File\Transfer` component, but it's kept primarily because some users had ported existing ZF1 code to ZF2. (As noted, it also contains a couple utilities outside the file transfer subcomponent.)

We'll be fixing #19 soon; this was an example of a new feature revealing a lack of tests, leading to broken functionality for some users once merged. (One note: I'd argue with the new feature making it "broken"; you should _never_ rely on the client-supplied filename, and depending on the file having the same name as transmitted by the client is a potential security vector! Since #19 changes the names, I'd argue it's _more secure_ now.)

**Comment by yourithielen** [comment]
Thanks for your reply @weierophinney.

The problems we were having were also related to #15. We use the file name supplied by getFileInfo() only for displaying it to the user, not for the actual filename on disk.
